### ISSUE TITLE
Tickets showing up linked to ITIL Services

### ISSUE THREAD

**Issue by raregtp** [bacus99/Services#10]
Right now we have four ITIL Services entered into the plugin.  All four of those services for some reason have the same three tickets liked to each ITIL Service.  I cannot see anywhere on a plugin how to link the plugin to an ITIL service, nor do I see anywhere on the Service where I can link it to the ticket, even though there is a ticket tab.

What is the login on how these tickets are showing up linked to the ITIL Service?

**Comment by raregtp** [comment]
Additional Info

When looking at the AJAX debug on the Tickets tab on any of my ITIL Services, the following SQL appears to be the culprit:

SELECT DISTINCT `glpi_tickets`.*, `glpi_itilcategories`.`completename` AS catname , `glpi_entities`.`completename` AS entityname, `glpi_tickets`.`entities_id` AS entityID 
FROM `glpi_tickets` 
LEFT JOIN `glpi_groups_tickets` ON (`glpi_tickets`.`id` = `glpi_groups_tickets`.`tickets_id`) 
LEFT JOIN `glpi_tickets_users` ON (`glpi_tickets`.`id` = `glpi_tickets_users`.`tickets_id`) 
LEFT JOIN `glpi_suppliers_tickets` ON (`glpi_tickets`.`id` = `glpi_suppliers_tickets`.`tickets_id`) 
LEFT JOIN `glpi_itilcategories` ON (`glpi_tickets`.`itilcategories_id` = `glpi_itilcategories`.`id`) 
LEFT JOIN `glpi_tickettasks` ON (`glpi_tickets`.`id` = `glpi_tickettasks`.`tickets_id`) 
LEFT JOIN `glpi_items_tickets` ON (`glpi_tickets`.`id` = `glpi_items_tickets`.`tickets_id`) 
LEFT JOIN `glpi_entities` ON (`glpi_entities`.`id` = `glpi_tickets`.`entities_id`) 
WHERE (`glpi_items_tickets`.`items_id` = '466' AND `glpi_items_tickets`.`itemtype` = 'PluginServicesService') OR (glpi_tickets.status=1)
ORDER BY `glpi_tickets`.`date_mod` DESC LIMIT 500

The issue appears to be due to the portion of the WHERE clause - (glpi_tickets.status=1)

Not sure why tickets with a status of NEW would be being flagged to show up in every ITIL service.....thus far I cannot find where that SQL statement is being constructed.

**Comment by raregtp** [comment]
Any update or thoughts on this?

**Comment by bacus99** [comment]
HI,
Sorry for the delay

I just check and don't see this in mine. I don't have any ticket link to ITIL services


 Also, you cannot link ticket to ITIL services directly upon my tests, pretty strange.  Let me dig this

**Comment by bacus99** [comment]
Ok, able to reproduce, let me check that

**Comment by raregtp** [comment]
Actually I think it was a bug in Glpi....saw it in the fix list and I don't have the problem any more on the latest Glpi release.

Matt
________________________________

**Comment by bacus99** [comment]
Corrected with version 9.1.4, you're right

Thank you!
