### ISSUE TITLE
can't install the version 1.0.6 on GLPi 9.2.3

### ISSUE THREAD

**Issue by calvin358** [bacus99/Services#12]
I got a " This plugin requires GLPI >= 9.1" error when I installed the plugin 1.0.6 version on GLPi 9.2.3.  The same plugin works fine on GLPi 9.1.4.  I guess there must be a bug somewhere. 

Thanks!
![untitled](https://user-images.githubusercontent.com/41791582/43322649-9f47248a-9185-11e8-8445-5198833c94bb.png)

**Comment by bacus99** [comment]
Try to adjust the setup.php file to change the version to 9.2 to 9.3

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : calvin358 <notifications@github.com>
Envoyé : Friday, July 27, 2018 9:18:40 AM
À : bacus99/Services
Cc : Subscribed
Objet : [bacus99/Services] can't install the version 1.0.6 on GLPi 9.2.3 (#12)


I got a " This plugin requires GLPI >= 9.1" error when I installed the plugin 1.0.6 version on GLPi 9.2.3. The same plugin works fine on GLPi 9.1.4. I guess there must be a bug somewhere.

Thanks!
[untitled]<https://user-images.githubusercontent.com/41791582/43322649-9f47248a-9185-11e8-8445-5198833c94bb.png>
