### ISSUE TITLE
Add more than one item associated with a service

### ISSUE THREAD

**Issue by victoria1984** [bacus99/Services#13]
Hello,
I am defining a new service and I have added an entity associated with the service.
I also want to add a network device, but when I add it, it does not report an error, but it does not link it as an associated element either.
Can the plugin add more than one associated element? How can I make these associations?
Thank you.

**Comment by victoria1984** [comment]
Also, once an element is linked to the service, it does not allow me to delete it, it returns an authorization problem even though I have a superadmin profile.
How can I delete an assignment?

**Comment by bacus99** [comment]
Hi Victoria, can you please send me the log file of your glpi installation? /glpi/files/*txt file


________________________________
De : victoria1984 <notifications@github.com>
Envoyé : Saturday, September 22, 2018 7:59:21 AM
À : bacus99/Services
Cc : Subscribed
Objet : Re: [bacus99/Services] Add more than one item associated with a service (#13)


Also, once an element is linked to the service, it does not allow me to delete it, it returns an authorization problem even though I have a superadmin profile.
How can I delete an assignment?

**Comment by victoria1984** [comment]
Yes, of course, I send you the complete _Log folder


[_log.zip](https://github.com/bacus99/Services/files/2409957/_log.zip)
