### ISSUE TITLE
no Save button

### ISSUE THREAD

**Issue by aldiop** [bacus99/Services#4]
Dear 
We cannot find the save button in the plugin. we are using GLPI 9.1.2.

Thanks
![itil services](https://cloud.githubusercontent.com/assets/21196684/23651743/c2eca980-0326-11e7-8ef4-7c9641ab141c.JPG)

**Comment by bacus99** [comment]
SQL file corrected, please validate with version 1.0.5

Tested onm V9.1.2

**Comment by aldiop** [comment]
Hi
I have this error when I tried to install the new plugin
update itemtype of table glpi_plugin_services_services_items for - Error during the database query: UPDATE `glpi_plugin_services_services_items` SET `itemtype` = '' WHERE `itemtype` = '0' - Error is Table 'glpidb.glpi_plugin_services_services_items' doesn't exist

**Comment by bacus99** [comment]
Uninstall the plugin, delete the folder and recopy

**Comment by aldiop** [comment]
Working fine

**Comment by bacus99** [comment]
Cool, let me know if you see some "improvement" possible

**Comment by aldiop** [comment]
It can be cool if we could associate the ITIL services with appliances or Certificates and IP adressing

**Comment by bacus99** [comment]
Hi aldiop, you currently can assign FROM certificate

![image](https://cloud.githubusercontent.com/assets/11425241/24160947/7c88116e-0e39-11e7-8a5b-bf485dbd15ff.png)


and FROM ITIL Services

![image](https://cloud.githubusercontent.com/assets/11425241/24161021/b28b60e0-0e39-11e7-8697-628dc46426e7.png)

**Comment by bacus99** [comment]
About IP Addressing, code may need to be updated.  I'll check that eventually

All ENVIRONMENT plugin content should be able to match with ITIL Services
