### ISSUE TITLE
No Not CSRF compliant

### ISSUE THREAD

**Issue by bacus99** [bacus99/Services#6]
To correct

**Comment by fabiobellotti** [comment]
I am still facing the issue, any work around?

**Comment by bacus99** [comment]
Not sure what is the error exactly...  In my dev environment, it indicate YES

In the setup file, do you have 

   // CSRF compliance : All actions must be done via POST and forms closed by Html::closeForm(); 
   $PLUGIN_HOOKS['csrf_compliant']['services'] = true;


You may have an older version

Let me know

**Comment by fabiobellotti** [comment]
sorry, I haven´t change the directory name to "services" before try it, so I got  CSRF compliant = No.. anyway, it is working, my bad bro...

**Comment by bacus99** [comment]
I'll check that


________________________________
De : fabiobellotti <notifications@github.com>
Envoyé : 21 mars 2017 10:34
À : bacus99/Services
Cc : Christian Bernard; Author
Objet : Re: [bacus99/Services] No Not CSRF compliant (#6)


sorry, I haven´t change the directory name to "services" before try it, so I got CSRF compliant = No.. anyway, it is working, my bad bro...

**Comment by m-benites** [comment]
I had the same error, but it was because I had the folder named "Services" with a capital "S" and after I changed to "services" it worked fine.

**Comment by bacus99** [comment]
Version #11 under tests, thank you

**Comment by bacus99** [comment]
Now compliant
