### ISSUE TITLE
Installation Error SQL

### ISSUE THREAD

**Issue by wernermarcel** [bacus99/Services#7]
Hello , 

we has glpi 9.1.2. 
Installed the latest plugin and get the error : 

update itemtype of table glpi_plugin_services_services_items for - Error during the database query: UPDATE `glpi_plugin_services_services_items` SET `itemtype` = '' WHERE `itemtype` = '0' - Error is Table 'GLPI.glpi_plugin_services_services_items' doesn't exist

rg
marcel

**Comment by wernermarcel** [comment]
if i load the sql/empty-1.0.0.sql by hand to the database the plugin is possible to install

**Comment by bacus99** [comment]
Good, we had this issue when V 1.0.4 was installed before


Is everything OK?


________________________________
De : wernermarcel <notifications@github.com>
Envoyé : 21 mars 2017 12:21
À : bacus99/Services
Cc : Subscribed
Objet : Re: [bacus99/Services] Installation Error SQL (#7)


if i load the sql/empty-1.0.0.sql by hand to the database the plugin is possible to install

**Comment by wernermarcel** [comment]
Now is all ok. But I think it should be a hint to load empty before blank instzall.

Rg
Marcel

**Comment by bacus99** [comment]
Hi Marcel,

Next version SQL install will be reworked

Thank you for you comments
