### ISSUE TITLE
Primary key in table glpi_plugin_services_services_items is not set to AUTO_INCREMENT

### ISSUE THREAD

**Issue by grzesiekn** [bacus99/Services#8]
Primary key in table glpi_plugin_services_services_items is not set to AUTO_INCREMENT

**Comment by bacus99** [comment]
-- AUTO_INCREMENT for table `glpi_plugin_services_services_items`
--
ALTER TABLE `glpi_plugin_services_services_items`;
	MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=8;

Will be set in next version

**Comment by bacus99** [comment]
Version bug #11 currently under tests, thank you

**Comment by bacus99** [comment]
Include in the new version
