### ISSUE TITLE
Locations under Location Dropdown cannot be viewed when plugin is enabled

### ISSUE THREAD

**Issue by raregtp** [bacus99/Services#9]
When the Services plugin is enabled, any locations that existed before the plugin was installed just sit at Loading on the main Location tab.  If the Services plugin is disabled, the locations display just fine.  If a new location is added after the Services plugin is installed, that location will display normally whether or not the Services plugin is Enabled or Disabled.

Services plugin version 1.06, GLPI version 9.1.2 and 9.1.3.

**Comment by raregtp** [comment]
Addtionally, turning on Debug in GLPI shows this error on Locations when the plugin is enabled:

Fatal error: Call to a member function fetch_assoc() on boolean in /var/www/html/glpi/inc/dbmysql.class.php on line 308

**Comment by raregtp** [comment]
Additionally, if the lines 230 and 231 are commented out in the hook.php file, the above errors disappear.

**Comment by raregtp** [comment]
Thoughts?

**Comment by bacus99** [comment]
Those 2 lines?

                        => array("glpi_plugin_services_services" => "groups_id_tech"),
                   "glpi_suppliers"

**Comment by raregtp** [comment]
I think so.....not able to jump online at the moment to verify, will try later.

Matt
________________________________

**Comment by raregtp** [comment]
Ok....not the two lines you have, but the two bolded below.

207 // Define dropdown relations
    208 function plugin_services_getDatabaseRelations() {
    209
    210    $plugin = new Plugin();
    211
    212    if ($plugin->isActivated("services")) {
    213       return array("glpi_plugin_services_servicetypes"
    214                         => array("glpi_plugin_services_services"
    215                                     => "plugin_services_servicetypes_id"),
    216                    "glpi_plugin_services_serviceservertypes"
    217                         => array("glpi_plugin_services_services"
    218                                     =>"plugin_services_serviceservertypes_id"),
    219                    "glpi_plugin_services_servicetechnics"
    220                         => array("glpi_plugin_services_services"
    221                                     =>"plugin_services_servicetechnics_id"),
    222                    "glpi_users"
    223                         => array("glpi_plugin_services_services" => "users_id_tech"),
    224                    "glpi_groups"
    225                         => array("glpi_plugin_services_services" => "groups_id_tech"),
    226                    "glpi_suppliers"
    227                         => array("glpi_plugin_services_services" => "suppliers_id"),
    228                    "glpi_manufacturers"
    229                         => array("glpi_plugin_services_services" => "manufacturers_id"),
    **230 //                   "glpi_locations"
    231 //                        => array("glpi_plugin_services_services" => "locations_id"),**
    232                    "glpi_plugin_services_services"
    233                         => array("glpi_plugin_services_services_items"
    234                                     => "plugin_services_services_id"),
    235                    "glpi_entities"
    236                         => array("glpi_plugin_services_services"     => "entities_id",
    237                                  "glpi_plugin_services_servicetypes" => "entities_id"));
    238    }
    239    return array();
    240 }

**Comment by bacus99** [comment]
Hi Matt, version 1.3.1 is under test for issue#11.  Can you test it in dev?
